// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw4UzcjHs0LocWmm71YstGBob4yikeqsQ',
    appId: '1:428641303325:web:9af3b8be76067cb8f67ff4',
    messagingSenderId: '428641303325',
    projectId: 'speedy-send-96a55',
    authDomain: 'speedy-send-96a55.firebaseapp.com',
    storageBucket: 'speedy-send-96a55.firebasestorage.app',
    measurementId: 'G-GHCQJ8V4TW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfvyR-p8tSFs_tTyWp_-M60n8_YKKFl3g',
    appId: '1:428641303325:android:38c87bec24860062f67ff4',
    messagingSenderId: '428641303325',
    projectId: 'speedy-send-96a55',
    storageBucket: 'speedy-send-96a55.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_-PZpOsOuBw3670U6c4LVmCmF3GbmIHg',
    appId: '1:428641303325:ios:85a7e6d6873f50bcf67ff4',
    messagingSenderId: '428641303325',
    projectId: 'speedy-send-96a55',
    storageBucket: 'speedy-send-96a55.firebasestorage.app',
    iosBundleId: 'com.example.deliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_-PZpOsOuBw3670U6c4LVmCmF3GbmIHg',
    appId: '1:428641303325:ios:85a7e6d6873f50bcf67ff4',
    messagingSenderId: '428641303325',
    projectId: 'speedy-send-96a55',
    storageBucket: 'speedy-send-96a55.firebasestorage.app',
    iosBundleId: 'com.example.deliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAw4UzcjHs0LocWmm71YstGBob4yikeqsQ',
    appId: '1:428641303325:web:4ea748cde6ac61dff67ff4',
    messagingSenderId: '428641303325',
    projectId: 'speedy-send-96a55',
    authDomain: 'speedy-send-96a55.firebaseapp.com',
    storageBucket: 'speedy-send-96a55.firebasestorage.app',
    measurementId: 'G-EEBWJ225S0',
  );
}
